language: emacs-lisp
dist: trusty
# https://github.com/travis-ci/travis-ci/issues/9061
sudo: required
matrix:
  allow_failures:
    - env: EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.3
    - env: EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.5
env:
  - EMACS_VERSION=26-pretest ZMQ_VERSION=4.2.3
  - EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.3
  - EMACS_VERSION=26-pretest ZMQ_VERSION=4.2.5
  - EMACS_VERSION=git-snapshot ZMQ_VERSION=4.2.5
before_install:
  # Setup paths
  - export PATH=${TRAVIS_BUILD_DIR}/.evm/bin:${TRAVIS_BUILD_DIR}/.cask/bin:${PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/lib:${LD_LIBRARY_PATH}
  - sudo apt-get update
  # Install emacs
  - if [[ ${EMACS_VERSION} = git-snapshot ]]; then sudo apt-get install -y texinfo; fi
  # Use this fork of EVM for dynamic module support
  - git clone https://github.com/ubolonton/evm ${TRAVIS_BUILD_DIR}/.evm
  - evm config path /tmp
  - evm install emacs-${EMACS_VERSION} --use --skip
  # Install cask
  - git clone https://github.com/cask/cask ${TRAVIS_BUILD_DIR}/.cask
  # Install zmq
  - git clone git://github.com/zeromq/libzmq.git
  - cd libzmq
  - git checkout v${ZMQ_VERSION}
  - mkdir cmake-build && cd cmake-build
  - cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR} .. && make && make install
install:
  - sudo apt-get install -y python3 python3-pip
  - sudo pip3 install --upgrade setuptools pip
  # --ignore-installed six since jupyter tries to upgrade it
  - sudo pip3 install --ignore-installed six jupyter
  # Install the kernelspec using the right python. Jupyter installs a default
  # python kernelspec that uses "python" for the command in
  # /usr/local/share/jupyter
  - sudo python3 -m ipykernel.kernelspec
  - cd $TRAVIS_BUILD_DIR
  - make dev
script:
  - cd $TRAVIS_BUILD_DIR
  # Build variables for zmq
  - export CFLAGS=-I${TRAVIS_BUILD_DIR}/include
  - export LDFLAGS=-L${TRAVIS_BUILD_DIR}/lib
  # For consistency with time encoding/decoding tests
  - export TZ=UTC0
  # Ensure Jupyter runtime dir can be written to
  - mkdir -p $(jupyter --runtime-dir)
  - jupyter --runtime-dir
  - jupyter --paths
  - jupyter kernelspec list
  - make test
